spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/episode?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jay-123456!